### ISSUE TITLE
Did you know that on facebook (n) is resolved to 👎 ?

### ISSUE THREAD

**Issue by ashnur** [okTurtles/groupcurrency.org#8]
maybe consider changing this part https://github.com/okTurtles/groupcurrency.org/blame/79ada11ce9cc41b2eaef4cfe4c5b4a3a87f5705a/index.md#L7

after all, it's not like it's used anywhere else on the page.

**Comment by taoeffect** [comment]
I'm confused as to what the use case is? The page isn't displayed on Facebook, so it shouldn't matter?

**Comment by ashnur** [comment]
Don't change it then. I mean, it's important to have stuff that is usually irrelevant and sometimes horrible instead. Gives life some spice n stuff.
